### ISSUE TITLE
Updating your code to the newest Chromaprint version?

### ISSUE THREAD

**Issue by PeterCodar** [protyposis/Aurio#1]
The original author of Chromaprint has updates his version to 1.4 recently:
https://github.com/acoustid/chromaprint/releases/tag/v1.4.2

Could you please have a look and update your C# code with the new changes?

**Comment by protyposis** [comment]
Looking at the 1.4.x changelogs, it seems that the changes have either already been implemented in Aurio or are not relevant.

Can you confirm my code is not compatible with Chromaprint any more?

**Comment by PeterCodar** [comment]
I can't confirm that your code is not compatible anymore. It just lacks of some nice features like the JSON output or the ability to fingerprint (partial) streams.

**Comment by protyposis** [comment]
Aurio has been designed for stream processing and fingerprinting of streams from the beginning, so this is definitely implemented.

There's no JSON output because Aurio doesn't focus on output formats. It provides raw fingerprints and it's up to the user to handle them (e.g. save as JSON). If you look at the [https://github.com/protyposis/Aurio#generate-fingerprints](Generate fingerprints) example, the `SubFingerprintsGenerated` listener receives the raw fingerprints and you can easily save them to JSON from there.

**Comment by PeterCodar** [comment]
I see, thank you for your explanation.

I found your project because is listed as "_C# (reimplementation)_" of chromaprint on https://github.com/acoustid/chromaprint

**Comment by protyposis** [comment]
Ok, thanks for letting me know!
